[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm run build"
  healthcheckPath = "/index.html"
  healthcheckTimeout = 100

[env]
  NODE_ENV = "production"
  VITE_API_URL = "https://worker-production-cbde.up.railway.app"
