[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm run build && npx http-server dist -p 8080 -c-1"
  port = 8080
  healthcheckPath = "/"
  healthcheckTimeout = 100

[env]
  NODE_ENV = "production"
  VITE_API_URL = "https://worker-production-cbde.up.railway.app"
