[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm run build"
  healthcheckPath = "/"
  healthcheckTimeout = 100
  staticPublishPath = "dist"

[env]
  NODE_ENV = "production"
  VITE_API_URL = "https://worker-production-cbde.up.railway.app"
